# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_unit', models.CharField(max_length=20)),
                ('chap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Fill_Question',
            fields=[
            ],
            options={
                'verbose_name': 'A Fill in The Blank Question',
                'verbose_name_plural': 'Fill in The Blank Questions',
                'proxy': True,
            },
            bases=('App.question',),
        ),
        migrations.CreateModel(
            name='Five_Marks_Question',
            fields=[
            ],
            options={
                'verbose_name': '5 Marks Question',
                'verbose_name_plural': '5 Marks Questions',
                'proxy': True,
            },
            bases=('App.question',),
        ),
        migrations.CreateModel(
            name='Four_Marks_Question',
            fields=[
            ],
            options={
                'verbose_name': '4 Marks Question',
                'verbose_name_plural': '4 Marks Questions',
                'proxy': True,
            },
            bases=('App.question',),
        ),
        migrations.CreateModel(
            name='MCQ_Marks_Question',
            fields=[
            ],
            options={
                'verbose_name': 'Multiple Choice Question',
                'verbose_name_plural': 'Multiple Choice Questions',
                'proxy': True,
            },
            bases=('App.question',),
        ),
        migrations.CreateModel(
            name='One_Marks_Question',
            fields=[
            ],
            options={
                'verbose_name': '1 Marks Question',
                'verbose_name_plural': '1 Marks Questions',
                'proxy': True,
            },
            bases=('App.question',),
        ),
        migrations.CreateModel(
            name='Three_Marks_Question',
            fields=[
            ],
            options={
                'verbose_name': '3 Marks Question',
                'verbose_name_plural': '3 Marks Questions',
                'proxy': True,
            },
            bases=('App.question',),
        ),
        migrations.CreateModel(
            name='Two_Marks_Question',
            fields=[
            ],
            options={
                'verbose_name': '2 Marks Question',
                'verbose_name_plural': '2 Marks Questions',
                'proxy': True,
            },
            bases=('App.question',),
        ),
        migrations.AddField(
            model_name='concepts',
            name='sub_unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Sub_Units'),
        ),
        migrations.AddField(
            model_name='question',
            name='concept',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sub_unit', chained_model_field='sub_unit_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='App.Concepts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='sub_unit',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='chap_id', chained_model_field='sub_unit', default=0, on_delete=django.db.models.deletion.CASCADE, to='App.Sub_Units'),
            preserve_default=False,
        ),
    ]
