# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20161205_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_units',
            name='sub_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App.Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sub_units',
            name='chap_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sub_id', chained_model_field='sub_id', on_delete=django.db.models.deletion.CASCADE, to='App.Chapter'),
        ),
    ]
