# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 07:07
from __future__ import unicode_literals

import App.models
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20161205_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='question',
            name='explaination',
            field=models.CharField(blank=True, default='No Explaination', max_length=500, null=True, verbose_name='Explaination'),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.CharField(default='Default Hint', max_length=35, verbose_name='Hint to the Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='related_file_answer',
            field=models.FileField(blank=True, null=True, upload_to=App.models.Question.upload_handler, verbose_name='Upload the Answer Documents'),
        ),
        migrations.AlterField(
            model_name='question',
            name='chap_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sub_id', chained_model_field='sub_id', on_delete=django.db.models.deletion.CASCADE, to='App.Chapter', verbose_name='Chapter '),
        ),
        migrations.AlterField(
            model_name='question',
            name='concept',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sub_unit', chained_model_field='sub_unit_id', on_delete=django.db.models.deletion.CASCADE, to='App.Concepts', verbose_name='Concept '),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default=None, max_length=100, verbose_name='Question '),
        ),
        migrations.AlterField(
            model_name='question',
            name='related_file',
            field=models.FileField(blank=True, null=True, upload_to=App.models.Question.upload_handler, verbose_name='Upload the Related Question Documents'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Subject', verbose_name='Subject '),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_unit',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='chap_id', chained_model_field='chap_id', on_delete=django.db.models.deletion.CASCADE, to='App.Sub_Units', verbose_name='Sub-Unit '),
        ),
    ]
