# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20161205_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.CharField(default='hint', max_length=35, verbose_name='Hint to the Question'),
            preserve_default=False,
        ),
    ]
