# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20161206_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explaination',
        ),
        migrations.RemoveField(
            model_name='question',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='question',
            name='related_file_answer',
        ),
    ]
