# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 07:13
from __future__ import unicode_literals

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20161206_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explaination',
            field=models.CharField(blank=True, default='No Explaination', max_length=500, null=True, verbose_name='Explaination'),
        ),
        migrations.AddField(
            model_name='question',
            name='related_file_answer',
            field=models.FileField(blank=True, null=True, upload_to=App.models.Question.upload_handler, verbose_name='Upload the Answer Documents'),
        ),
    ]
