# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20161206_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explaination',
            field=models.CharField(blank=True, default='No Explaination', max_length=140, null=True, verbose_name='Explaination'),
        ),
    ]
