# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20161206_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explaination',
            field=models.TextField(blank=True, default='No Explaination', max_length=500, null=True, verbose_name='Explaination'),
        ),
    ]
