# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20161206_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_answer',
            name='correct_answer',
            field=models.CharField(choices=[('option_1', 'A'), ('option_2', 'B'), ('option_3', 'C'), ('option_4', 'D')], max_length=10),
        ),
    ]
